# -*- coding: utf-8 -*-
"""Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCAwT61nMyWudjwZhG9X98pYcBHskUNb

Instalación de librerias
"""

!pip install roboflow ultralytics

"""Descargar dataset

"""

from roboflow import Roboflow
rf = Roboflow(api_key="API_KEY")
project = rf.workspace("my-office-uk1fg").project("movil_app-qvgra")
version = project.version(1)
dataset = version.download("yolov8")

"""Carga de modelo base"""

from ultralytics import YOLO
model = YOLO("yolov8n.pt")

"""Entrenamiento personalizado"""

data_path = "/content/movil_app-1/data.yaml"

model.train(
    data=data_path,
    epochs=50,
    imgsz=640
)

"""Prediccion"""

custom_model=YOLO("/content/runs/detect/train/weights/best.pt")

res =custom_model("/content/movil_app-1/test/images")

res[14].show()

!yolo export model="" format=tflite